<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYmyrfct\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYmyrfct/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYmyrfct.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYmyrfct\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYmyrfct\appProdProjectContainer([
    'container.build_hash' => 'Ymyrfct',
    'container.build_id' => 'fda59bd6',
    'container.build_time' => 1569850172,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYmyrfct');
