<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAcunmxx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAcunmxx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAcunmxx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAcunmxx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAcunmxx\appDevDebugProjectContainer([
    'container.build_hash' => 'Acunmxx',
    'container.build_id' => 'ae1004d3',
    'container.build_time' => 1589399000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAcunmxx');
