<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xvsr0k\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xvsr0k/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5xvsr0k.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5xvsr0k\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5xvsr0k\appDevDebugProjectContainer([
    'container.build_hash' => '5xvsr0k',
    'container.build_id' => '191ce6ba',
    'container.build_time' => 1589960620,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xvsr0k');
